Repository acm-ucr/aag-website, pull requests merged in 2023-11, with the labels that each got.

#57 I added the red stripes.
  src/components/ImageBars.jsx
Labels: Home, Ready for Review

#85 fix mobile responsiveness
  src/components/JoinIcon.jsx
  src/components/JoinIcons.jsx
Labels: Home, Mobile Responsiveness

#84 I improved mobile responsiveness of footer.
  src/components/Footer.jsx
Labels: Home, Ready for Review, Mobile Responsiveness

#104 minor fixes
  src/components/NavBar.jsx
Labels: Home, Boards, About

#107 I added the video component
  src/components/Video.jsx
Labels: About, Ready for Review

#110 Sreeja pagireddy/title
  src/app/board/page.js
  src/components/JoinButton.jsx
Labels: bug
