Repository acm-ucr/aag-website, pull requests merged in 2023-10, with the labels that each got.

#16 change boards page
  src/app/boards/page.js
Labels: Boards, Ready for Review

#18 Atharva/new image bars
  public/image_1.png
  public/image_2.png
  public/image_3.png
  public/image_4.png
  public/image_5.png
  src/components/ImageBars.jsx
Labels: Home

#21 Footer
  src/components/Footer.jsx
Labels: Home, Boards, Events

#25 I added the TextBlock component.
  src/components/TextBlock.jsx
Labels: Home, Ready for Review

#23 Create JoinIcon Component
  src/components/JoinIcon.jsx
Labels: Home, Ready for Review

#38 I added the JoinIcons component
  src/components/JoinIcons.jsx
Labels: Home, Ready for Review

#42 issue8
  src/components/NavBar.jsx
Labels: Home, Boards, Events

#44 pushing
  src/app/boards/page.js
  src/components/Boards.jsx
  src/data/boards.js
Labels: Boards

#45 pushing
  src/app/boards/page.js
  src/components/Boards.jsx
  src/data/boards.js
Labels: bug
